FROM nodered/node-red:latest-minimal

# NodeRED Dashboard
RUN npm install node-red-dashboard
# NodeRED Gauge for Dashboard
RUN npm install node-red-contrib-ui-artless-gauge
# NodeRED Login System
RUN npm install node-red-contrib-users
# NodeRED MySQL Connector
RUN npm install node-red-node-mysql
# Update Node.JS Package
RUN npm update
