FROM nodered/node-red:latest-minimal

# NodeRED Dashboard
RUN npm install node-red-dashboard

# NodeRED Gauge for Dashboard
RUN npm install node-red-contrib-ui-artless-gauge

# NodeRED MySQL Connector
RUN npm install node-red-node-mysql

#NodeRED Telegram Bot
RUN npm install node-red-contrib-telegrambot

#NodeRED Iframe
RUN npm install node-red-node-ui-iframe

#NodeRED Iframe
RUN npm install @sherlock-gmbh/node-red-contrib-ui-iframe-modal
